### ISSUE TITLE
/pvp set doesn't work properly

### ISSUE THREAD

**Issue by Kjenium** [jkorn2324/PvPCore-PMMP#3]
/pvp set level knockback/attackdelay value doesn't work if you put knockback or attackdelay  in the second argument but only works with kb and delay

**Comment by Kjenium** [comment]
I hope this will be fixed in the future

**Comment by jkorn2324** [comment]
I will look into this when I have extra time. Thanks for reporting this

**Comment by Kjenium** [comment]
Just made a pull request with the fix. Just Merge Me and Ruby's commits to completely fix
